// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Survey.Persistence;

namespace Survey.Persistence.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    partial class SurveyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Survey.Domain.Survey.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreateAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<int>("OrderIndex");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Answer");
                });

            modelBuilder.Entity("Survey.Domain.Survey.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("AnaliticsType");

                    b.Property<string>("Description");

                    b.Property<bool>("IsOpen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Survey.Domain.Survey.FormUser", b =>
                {
                    b.Property<int>("FormId");

                    b.Property<int>("UserId");

                    b.HasKey("FormId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FormsUsers");
                });

            modelBuilder.Entity("Survey.Domain.Survey.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("CustomErrorMessage");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsRequired");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Question");
                });

            modelBuilder.Entity("Survey.Domain.Survey.QuestionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreateAt");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("QuestionId");

                    b.Property<int>("SurveyResultId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyResultId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestionResponses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("QuestionResponse");
                });

            modelBuilder.Entity("Survey.Domain.Survey.Result.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionType");

                    b.Property<bool>("Active");

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<int>("FormId");

                    b.Property<bool>("IsCompleted");

                    b.Property<DateTime>("StartedAt");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("Survey.Domain.Survey.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<int>("FormId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Survey.Domain.Survey.SectionQuestion", b =>
                {
                    b.Property<int>("SectionId");

                    b.Property<int>("QuestionId");

                    b.Property<int>("QuestionOrderIndex");

                    b.HasKey("SectionId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("SectionsQuestions");
                });

            modelBuilder.Entity("Survey.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Survey.Domain.Survey.CheckBoxAnswer", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Answer");

                    b.Property<bool>("IsSelected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.ToTable("CheckBoxAnswers");

                    b.HasDiscriminator().HasValue("CheckBoxAnswer");
                });

            modelBuilder.Entity("Survey.Domain.Survey.RadioButtonAnswer", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Answer");

                    b.Property<int>("GoToSection");

                    b.Property<bool>("IsSelected")
                        .HasColumnName("RadioButtonAnswer_IsSelected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("RadioButtonAnswer_Name")
                        .HasMaxLength(50);

                    b.ToTable("RadioButtonAnswers");

                    b.HasDiscriminator().HasValue("RadioButtonAnswer");
                });

            modelBuilder.Entity("Survey.Domain.Survey.TextAnswer", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Answer");

                    b.Property<string>("Text")
                        .HasMaxLength(100);

                    b.ToTable("TextAnswers");

                    b.HasDiscriminator().HasValue("TextAnswer");
                });

            modelBuilder.Entity("Survey.Domain.Survey.CheckBoxesQuestion", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Question");


                    b.ToTable("CheckBoxesQuestions");

                    b.HasDiscriminator().HasValue("CheckBoxesQuestion");
                });

            modelBuilder.Entity("Survey.Domain.Survey.RadioButtonsQuestion", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Question");


                    b.ToTable("RadioButtonsQuestions");

                    b.HasDiscriminator().HasValue("RadioButtonsQuestion");
                });

            modelBuilder.Entity("Survey.Domain.Survey.ShortQuestion", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.Question");


                    b.ToTable("ShortQuestions");

                    b.HasDiscriminator().HasValue("ShortQuestion");
                });

            modelBuilder.Entity("Survey.Domain.Survey.CheckBoxQuestionResponse", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.QuestionResponse");

                    b.Property<bool>("IsSelected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OtherText");

                    b.ToTable("CheckBoxQuestionResponses");

                    b.HasDiscriminator().HasValue("CheckBoxQuestionResponse");
                });

            modelBuilder.Entity("Survey.Domain.Survey.RadioButtonQuestionResponse", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.QuestionResponse");

                    b.Property<bool>("IsSelected")
                        .HasColumnName("RadioButtonQuestionResponse_IsSelected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("RadioButtonQuestionResponse_Name")
                        .HasMaxLength(50);

                    b.Property<string>("OtherText")
                        .HasColumnName("RadioButtonQuestionResponse_OtherText");

                    b.ToTable("RadioButtonQuestionResponses");

                    b.HasDiscriminator().HasValue("RadioButtonQuestionResponse");
                });

            modelBuilder.Entity("Survey.Domain.Survey.TextQuestionResponse", b =>
                {
                    b.HasBaseType("Survey.Domain.Survey.QuestionResponse");

                    b.Property<string>("Text")
                        .HasMaxLength(100);

                    b.ToTable("TextQuestionResponses");

                    b.HasDiscriminator().HasValue("TextQuestionResponse");
                });

            modelBuilder.Entity("Survey.Domain.Survey.Answer", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Survey.Domain.Survey.FormUser", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Form", "Form")
                        .WithMany("FormUsers")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survey.Domain.Users.User", "User")
                        .WithMany("UserForms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Survey.Domain.Survey.QuestionResponse", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Question", "Question")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survey.Domain.Survey.Result.SurveyResult", "SurveyResult")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("SurveyResultId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survey.Domain.Users.User", "User")
                        .WithMany("QuestionResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Survey.Domain.Survey.Result.SurveyResult", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Form", "Form")
                        .WithMany("SurveyResults")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Survey.Domain.Survey.Section", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Form", "Form")
                        .WithMany("Sections")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Survey.Domain.Survey.SectionQuestion", b =>
                {
                    b.HasOne("Survey.Domain.Survey.Question", "Question")
                        .WithMany("QuestionSections")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Survey.Domain.Survey.Section", "Section")
                        .WithMany("SectionQuestions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
